#!/bin/bash

TARGET_DIR="codebase_10000"
mkdir -p "$TARGET_DIR"
for idx in $(seq -w 1 10000); do
    fname="$TARGET_DIR/source${idx}.dat"
    # Generate two stub lines:
    echo "// file #${idx} -- autogenerated" > "$fname"
    echo "int var_${idx} = ${idx};" >> "$fname"
done
echo "Done: 10,000 files in $TARGET_DIR."
